### PR TITLE
add Honeycomb exporter and example app

### PR DESCRIPTION
**Pull request by akvanhar**
Adds the Honeycomb exporter, tests and example app

### CODE REVIEW

**Comment by emfree** [comment]
It looks like vendor-specific OpenCensus exporters mostly live in their own repos, e.g. https://github.com/DataDog/opencensus-go-exporter-datadog . I reckon it might make sense for us to do the same, at least for the time being, i.e. make https://github.com/honeycombio/opencensus-exporter public. For one thing, that'll make it easier for us to merge changes quickly. Maybe this is a question for the OpenCensus folks as well.

**Comment by akvanhar** [comment]
I think some vendor-specific openCensus exporters live in their own repos, but at least 4 of them live within this repo on openCensus https://github.com/census-instrumentation/opencensus-go/tree/master/exporter. Up to us which way we'd like to go. The nice thing about hosting it ourselves is that it's easier to make changes, like you said.

**Comment by akvanhar** [comment]
Either way is fine by me. I'll send an email and ask which they prefer.

**Comment by akvanhar** [comment]
They agree with you. Closing this PR.

**Pull request closed without merging**
